name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit black flake8 mypy pytest coverage coverage-badge
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest
      - name: Generate coverage report with Coverage
        run:
          coverage run -m pytest
      - name: create Coverage badge
        run:
          coverage-badge -o coveragebadge.svg
      - name: stage changed badge file
        run: git add /home/runner/work/backend-assessment/backend-assessment/coveragebadge.svg
      - name: commit badge file
        run: git commit -m "coverage badge added"
      - name: fetch from master
        run: git fetch origin master
      - name: push badge to master
        run: git push origin HEAD:master
        
